export interface StorySlide {
  id: number
  type: 'intro' | 'scene' | 'insight' | 'problem' | 'solution' | 'conclusion'
  character?: 'happy' | 'thinking' | 'surprised' | 'excited' | 'confused' | 'pointing'
  characterPosition?: 'left' | 'right' | 'center'
  title?: string
  dialogue?: string
  content: string
  highlight?: string
  code?: string
  emoji?: string
}

export interface CaseStudy {
  id: string
  slug: string
  title: string
  description: string
  category: string
  readTime: string
  thumbnail: string
  color: string
  featured?: boolean
  // Detailed content
  subtitle?: string
  author?: string
  date?: string
  slides?: StorySlide[]
  takeaways?: string[]
  nextSlug?: string
  prevSlug?: string
}

export type Category = 'all' | 'llm' | 'agents' | 'prompts' | 'rag' | 'ux'

export interface Article {
  id: string
  title: string
  description: string
  category: Exclude<Category, 'all'>
  readTime: string
  thumbnail: string
}

export const categories = [
  { id: 'all' as Category, label: 'All' },
  { id: 'llm' as Category, label: 'LLMs' },
  { id: 'agents' as Category, label: 'AI Agents' },
  { id: 'prompts' as Category, label: 'Prompting' },
  { id: 'rag' as Category, label: 'RAG' },
  { id: 'ux' as Category, label: 'AI UX' },
]

export const caseStudies: CaseStudy[] = [
  {
    id: '1',
    slug: 'how-chatgpt-keeps-you-hooked',
    title: 'How ChatGPT Keeps You Hooked',
    description: 'The psychology behind OpenAI\'s addictive conversational design patterns.',
    subtitle: 'A deep dive into the UX psychology that makes ChatGPT irresistible',
    category: 'llm',
    readTime: '8 min',
    thumbnail: '/thumbnails/chatgpt.png',
    color: '#10B981',
    featured: true,
    author: 'AI Weekly',
    date: 'Jan 15, 2026',
    nextSlug: 'building-your-first-ai-agent',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '🎯',
        title: 'The Hook',
        content: 'Ever wondered why you can\'t stop chatting with ChatGPT? It\'s not magic—it\'s brilliant design psychology.',
        character: 'thinking',
        characterPosition: 'left',
        dialogue: 'Let me show you the secrets behind ChatGPT\'s addictive design...',
      },
      {
        id: 2,
        type: 'problem',
        emoji: '🧠',
        title: 'The Variable Reward Loop',
        content: 'Each response is slightly different, even for the same prompt. This unpredictability triggers dopamine release.',
        highlight: 'Your brain treats each response like a mini lottery win',
        character: 'surprised',
        characterPosition: 'right',
        dialogue: 'Wait... it\'s the same mechanism slot machines use!',
      },
      {
        id: 3,
        type: 'insight',
        emoji: '⚡',
        title: 'Streaming Creates Anticipation',
        content: 'Watching text appear word-by-word mimics human typing. This creates micro-moments of anticipation that keep you engaged.',
        code: 'for await (const chunk of stream) {\n  // Each chunk triggers anticipation\n  display(chunk)\n}',
        character: 'pointing',
        characterPosition: 'left',
        dialogue: 'See how each word builds suspense?',
      },
      {
        id: 4,
        type: 'solution',
        emoji: '💬',
        title: 'Conversational Memory',
        content: 'ChatGPT remembers your conversation context. This creates a sense of relationship—like chatting with a friend who knows your history.',
        highlight: 'Context memory creates artificial intimacy',
        character: 'happy',
        characterPosition: 'right',
        dialogue: 'It remembers me! We\'re basically friends now.',
      },
      {
        id: 5,
        type: 'insight',
        emoji: '🎨',
        title: 'Markdown Magic',
        content: 'Formatted responses with headers, bullets, and code blocks feel more valuable. Rich formatting triggers the "effort heuristic".',
        character: 'excited',
        characterPosition: 'left',
        dialogue: 'Higher perceived effort = higher perceived value!',
      },
      {
        id: 6,
        type: 'conclusion',
        emoji: '🚀',
        title: 'Design Your Own Hooks',
        content: 'These patterns aren\'t exclusive to OpenAI. You can implement streaming, memory, and rich formatting in your own AI applications.',
        highlight: 'Understanding the psychology helps you build better AI products',
        character: 'excited',
        characterPosition: 'center',
        dialogue: 'Now go build something amazing!',
      },
    ],
    takeaways: [
      'Variable rewards (unpredictable responses) trigger dopamine',
      'Streaming text creates engagement through anticipation',
      'Conversation memory builds artificial relationships',
      'Rich formatting increases perceived value',
      'These patterns can be ethically applied to your own AI apps',
    ],
  },
  {
    id: '2',
    slug: 'building-your-first-ai-agent',
    title: 'Building Your First AI Agent',
    description: 'A visual guide to creating autonomous agents that actually work.',
    subtitle: 'From zero to autonomous agent in 30 minutes',
    category: 'agents',
    readTime: '12 min',
    thumbnail: '/thumbnails/agents.png',
    color: '#8B5CF6',
    author: 'AI Weekly',
    date: 'Jan 10, 2026',
    prevSlug: 'how-chatgpt-keeps-you-hooked',
    nextSlug: 'prompt-engineering-secrets',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '🤖',
        title: 'What is an AI Agent?',
        content: 'An AI agent is more than a chatbot. It can think, plan, use tools, and take actions autonomously to achieve goals.',
        highlight: 'Agents = LLM + Tools + Memory + Goals',
        character: 'excited',
        characterPosition: 'left',
        dialogue: 'Agents are like having a smart assistant that can actually DO things!',
      },
      {
        id: 2,
        type: 'scene',
        emoji: '🧩',
        title: 'The Agent Loop',
        content: 'Agents work in a loop: Observe → Think → Act → Repeat. This simple pattern enables complex behaviors.',
        code: 'while (!goal_achieved) {\n  observation = perceive(environment)\n  thought = llm.reason(observation)\n  action = select_tool(thought)\n  result = execute(action)\n}',
        character: 'pointing',
        characterPosition: 'right',
        dialogue: 'This loop is the brain of every AI agent!',
      },
      {
        id: 3,
        type: 'solution',
        emoji: '🔧',
        title: 'Tools are Superpowers',
        content: 'Give your agent tools like web search, code execution, and API calls. Each tool expands what your agent can do.',
        highlight: 'A calculator tool makes your agent 100x better at math',
        character: 'happy',
        characterPosition: 'left',
        dialogue: 'Tools turn a chatbot into a superhero!',
      },
      {
        id: 4,
        type: 'insight',
        emoji: '🧠',
        title: 'Memory Matters',
        content: 'Short-term memory holds the current conversation. Long-term memory (vector DBs) stores knowledge across sessions.',
        character: 'thinking',
        characterPosition: 'right',
        dialogue: 'Without memory, agents forget everything between conversations.',
      },
      {
        id: 5,
        type: 'conclusion',
        emoji: '🎯',
        title: 'Start Simple',
        content: 'Your first agent doesn\'t need to be complex. Start with one tool, one goal, and iterate from there.',
        highlight: 'Complexity is the enemy of shipping',
        character: 'excited',
        characterPosition: 'center',
        dialogue: 'Ship fast, learn faster!',
      },
    ],
    takeaways: [
      'Agents combine LLMs, tools, memory, and goals',
      'The observe-think-act loop is the core pattern',
      'Tools expand agent capabilities exponentially',
      'Start with simple agents and add complexity gradually',
    ],
  },
  {
    id: '3',
    slug: 'prompt-engineering-secrets',
    title: 'Prompt Engineering Secrets',
    description: 'Advanced techniques the pros use to get better outputs from LLMs.',
    subtitle: 'The techniques that separate amateurs from experts',
    category: 'prompts',
    readTime: '6 min',
    thumbnail: '/thumbnails/prompts.png',
    color: '#F59E0B',
    author: 'AI Weekly',
    date: 'Jan 5, 2026',
    prevSlug: 'building-your-first-ai-agent',
    nextSlug: 'rag-explained-visually',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '✨',
        title: 'Prompts are Programs',
        content: 'Think of prompts as code for LLMs. Small changes in wording can dramatically change outputs.',
        highlight: 'A well-crafted prompt is worth 1000 fine-tuning examples',
        character: 'pointing',
        characterPosition: 'left',
        dialogue: 'Prompts are like code—but for AI!',
      },
      {
        id: 2,
        type: 'solution',
        emoji: '📝',
        title: 'The Role Technique',
        content: 'Start with "You are a [expert role]". This primes the model to respond with that expertise.',
        code: '"You are a senior software architect\\nwith 20 years of experience..."',
        character: 'happy',
        characterPosition: 'right',
        dialogue: 'Give the AI a character to play!',
      },
      {
        id: 3,
        type: 'insight',
        emoji: '🎯',
        title: 'Few-Shot Learning',
        content: 'Show 2-3 examples of input → output pairs. The model learns the pattern and applies it to new inputs.',
        highlight: 'Examples are the most powerful teaching tool',
        character: 'excited',
        characterPosition: 'left',
        dialogue: 'Show, don\'t tell!',
      },
      {
        id: 4,
        type: 'solution',
        emoji: '🔗',
        title: 'Chain of Thought',
        content: 'Add "Let\'s think step by step" to unlock reasoning. This simple phrase improves accuracy by 40%+.',
        code: '"Solve this problem.\\nLet\'s think step by step."',
        character: 'thinking',
        characterPosition: 'right',
        dialogue: 'This one trick makes AI 40% smarter!',
      },
      {
        id: 5,
        type: 'conclusion',
        emoji: '🚀',
        title: 'Iterate Relentlessly',
        content: 'The best prompts come from iteration. Test, measure, refine. Treat prompts like A/B tests.',
        character: 'excited',
        characterPosition: 'center',
        dialogue: 'Iterate until it\'s perfect!',
      },
    ],
    takeaways: [
      'Prompts are code—treat them with the same rigor',
      'Role prompts prime the model for expertise',
      'Few-shot examples are incredibly powerful',
      'Chain of thought improves reasoning significantly',
      'Iteration is key to prompt optimization',
    ],
  },
  {
    id: '4',
    slug: 'rag-explained-visually',
    title: 'RAG Explained Visually',
    description: 'How retrieval-augmented generation works, explained with comics.',
    subtitle: 'The architecture that powers enterprise AI',
    category: 'rag',
    readTime: '10 min',
    thumbnail: '/thumbnails/rag.png',
    color: '#EC4899',
    author: 'AI Weekly',
    date: 'Dec 28, 2025',
    prevSlug: 'prompt-engineering-secrets',
    nextSlug: 'designing-ai-that-feels-human',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '📚',
        title: 'The Knowledge Problem',
        content: 'LLMs have a knowledge cutoff and can\'t access your private data. RAG solves this by giving LLMs access to external knowledge.',
        highlight: 'RAG = Retrieval + LLM Generation',
        character: 'confused',
        characterPosition: 'left',
        dialogue: 'GPT doesn\'t know about YOUR documents...',
      },
      {
        id: 2,
        type: 'scene',
        emoji: '🔍',
        title: 'Step 1: Index',
        content: 'First, chunk your documents and convert them to vectors (embeddings). Store these in a vector database.',
        code: 'chunks = split(documents)\\nembeddings = embed(chunks)\\nvector_db.store(embeddings)',
        character: 'pointing',
        characterPosition: 'right',
        dialogue: 'Convert your docs into searchable vectors!',
      },
      {
        id: 3,
        type: 'solution',
        emoji: '🎯',
        title: 'Step 2: Retrieve',
        content: 'When a user asks a question, find the most similar chunks using vector similarity search.',
        highlight: 'Semantic search finds relevant content even with different wording',
        character: 'happy',
        characterPosition: 'left',
        dialogue: 'Finding needles in haystacks, instantly!',
      },
      {
        id: 4,
        type: 'insight',
        emoji: '✨',
        title: 'Step 3: Generate',
        content: 'Pass the retrieved chunks + user question to the LLM. The model generates an answer grounded in your data.',
        code: 'context = retrieve(question)\\nanswer = llm.generate(context + question)',
        character: 'excited',
        characterPosition: 'right',
        dialogue: 'Now the AI knows YOUR stuff!',
      },
      {
        id: 5,
        type: 'conclusion',
        emoji: '🚀',
        title: 'RAG in Production',
        content: 'RAG powers chatbots, search engines, and documentation assistants. It\'s the most practical way to add knowledge to LLMs.',
        character: 'excited',
        characterPosition: 'center',
        dialogue: 'The secret weapon of enterprise AI!',
      },
    ],
    takeaways: [
      'RAG combines retrieval with generation',
      'Vector embeddings enable semantic search',
      'Chunking strategy significantly impacts quality',
      'RAG is the most practical enterprise AI pattern',
    ],
  },
  {
    id: '5',
    slug: 'designing-ai-that-feels-human',
    title: 'Designing AI That Feels Human',
    description: 'UX patterns that make AI interfaces delightful to use.',
    subtitle: 'Creating AI experiences users actually love',
    category: 'ux',
    readTime: '7 min',
    thumbnail: '/thumbnails/aiux.png',
    color: '#3B82F6',
    author: 'AI Weekly',
    date: 'Dec 20, 2025',
    prevSlug: 'rag-explained-visually',
    nextSlug: 'fine-tuning-demystified',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '💝',
        title: 'AI UX is Different',
        content: 'AI interfaces are probabilistic, not deterministic. This requires new UX patterns to manage uncertainty.',
        highlight: 'Users need to trust AI before they\'ll use it',
        character: 'thinking',
        characterPosition: 'left',
        dialogue: 'AI is unpredictable... how do we design for that?',
      },
      {
        id: 2,
        type: 'solution',
        emoji: '⏳',
        title: 'Show the Thinking',
        content: 'Display progress indicators, streaming text, and status updates. Users are more patient when they can see work happening.',
        highlight: 'Perceived wait time < actual wait time when shown progress',
        character: 'pointing',
        characterPosition: 'right',
        dialogue: 'Show users that something is happening!',
      },
      {
        id: 3,
        type: 'insight',
        emoji: '🎚️',
        title: 'Provide Controls',
        content: 'Let users adjust temperature, length, and style. Control creates trust and reduces the "black box" feeling.',
        character: 'happy',
        characterPosition: 'left',
        dialogue: 'Give users control and they\'ll trust you!',
      },
      {
        id: 4,
        type: 'solution',
        emoji: '✅',
        title: 'Enable Verification',
        content: 'Show sources, citations, and confidence levels. Make it easy for users to verify AI outputs.',
        code: '// Always cite your sources\\n"According to [source]..."',
        character: 'pointing',
        characterPosition: 'right',
        dialogue: 'Cite your sources!',
      },
      {
        id: 5,
        type: 'conclusion',
        emoji: '🤝',
        title: 'AI as Collaborator',
        content: 'The best AI UX treats AI as a collaborator, not an oracle. Enable iteration, editing, and feedback.',
        character: 'happy',
        characterPosition: 'center',
        dialogue: 'AI works WITH you, not FOR you!',
      },
    ],
    takeaways: [
      'AI UX requires managing uncertainty',
      'Progress indicators reduce perceived wait time',
      'User controls build trust',
      'Citations and sources enable verification',
      'Position AI as a collaborator, not an authority',
    ],
  },
  {
    id: '6',
    slug: 'fine-tuning-demystified',
    title: 'Fine-Tuning Demystified',
    description: 'When and how to fine-tune models for your specific use case.',
    subtitle: 'The complete guide to customizing LLMs',
    category: 'llm',
    readTime: '9 min',
    thumbnail: '/thumbnails/finetuning.png',
    color: '#14B8A6',
    author: 'AI Weekly',
    date: 'Dec 15, 2025',
    prevSlug: 'designing-ai-that-feels-human',
    nextSlug: 'multi-agent-orchestration',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '🎓',
        title: 'What is Fine-Tuning?',
        content: 'Fine-tuning adapts a pre-trained model to your specific task using your own data. It\'s like specialized training.',
        highlight: 'Fine-tuning = Pre-trained model + Your data',
        character: 'thinking',
        characterPosition: 'left',
        dialogue: 'Think of it like teaching GPT YOUR style!',
      },
      {
        id: 2,
        type: 'problem',
        emoji: '🤔',
        title: 'When to Fine-Tune',
        content: 'Fine-tune when prompting isn\'t enough: specific formats, domain knowledge, or consistent style requirements.',
        highlight: 'Try prompting first—fine-tuning is a last resort',
        character: 'confused',
        characterPosition: 'right',
        dialogue: 'But wait... do you really need it?',
      },
      {
        id: 3,
        type: 'solution',
        emoji: '📊',
        title: 'Prepare Your Data',
        content: 'You need high-quality input/output pairs. Quality > quantity. 100 great examples beat 10,000 mediocre ones.',
        code: '{"messages": [\\n  {"role": "user", "content": "..."},\\n  {"role": "assistant", "content": "..."}\\n]}',
        character: 'pointing',
        characterPosition: 'left',
        dialogue: 'Quality over quantity, always!',
      },
      {
        id: 4,
        type: 'insight',
        emoji: '⚙️',
        title: 'LoRA: Efficient Fine-Tuning',
        content: 'LoRA (Low-Rank Adaptation) fine-tunes only a small number of parameters. It\'s faster, cheaper, and often just as good.',
        character: 'excited',
        characterPosition: 'right',
        dialogue: 'LoRA is a game-changer!',
      },
      {
        id: 5,
        type: 'conclusion',
        emoji: '🎯',
        title: 'Evaluate Rigorously',
        content: 'Always compare fine-tuned model vs. base model + good prompts. Fine-tuning isn\'t always the winner.',
        character: 'thinking',
        characterPosition: 'center',
        dialogue: 'Test everything. Trust nothing.',
      },
    ],
    takeaways: [
      'Fine-tuning customizes models with your data',
      'Try prompt engineering before fine-tuning',
      'Data quality matters more than quantity',
      'LoRA enables efficient, cost-effective fine-tuning',
      'Always evaluate against prompting baselines',
    ],
  },
  {
    id: '7',
    slug: 'multi-agent-orchestration',
    title: 'Multi-Agent Orchestration',
    description: 'Coordinating multiple AI agents to solve complex problems.',
    subtitle: 'Building teams of specialized AI agents',
    category: 'agents',
    readTime: '11 min',
    thumbnail: '/thumbnails/multiagent.png',
    color: '#A855F7',
    author: 'AI Weekly',
    date: 'Dec 10, 2025',
    prevSlug: 'fine-tuning-demystified',
    nextSlug: 'the-art-of-system-prompts',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '👥',
        title: 'Why Multi-Agent?',
        content: 'One agent can\'t do everything well. Multiple specialized agents can tackle complex problems together.',
        highlight: 'Specialization + Collaboration = Superpowers',
        character: 'excited',
        characterPosition: 'left',
        dialogue: 'What if we had a whole TEAM of AI agents?',
      },
      {
        id: 2,
        type: 'solution',
        emoji: '🏗️',
        title: 'Common Patterns',
        content: 'Supervisor: One agent coordinates others. Pipeline: Agents work in sequence. Debate: Agents critique each other.',
        code: 'supervisor.delegate(task, [agent1, agent2])\\nresults = await Promise.all(subtasks)\\nfinal = supervisor.synthesize(results)',
        character: 'pointing',
        characterPosition: 'right',
        dialogue: 'Three patterns to rule them all!',
      },
      {
        id: 3,
        type: 'insight',
        emoji: '💬',
        title: 'Agent Communication',
        content: 'Agents need clear protocols for sharing information. Structured messages prevent miscommunication.',
        character: 'thinking',
        characterPosition: 'left',
        dialogue: 'Agents need to talk to each other clearly!',
      },
      {
        id: 4,
        type: 'problem',
        emoji: '⚠️',
        title: 'Watch for Loops',
        content: 'Multi-agent systems can get stuck in infinite loops. Set maximum iterations and detect circular discussions.',
        highlight: 'Always implement circuit breakers',
        character: 'surprised',
        characterPosition: 'right',
        dialogue: 'Infinite loops = infinite bills! 😱',
      },
      {
        id: 5,
        type: 'conclusion',
        emoji: '🚀',
        title: 'Start with Two',
        content: 'Begin with two agents: a planner and an executor. Add more only when you hit clear limitations.',
        character: 'happy',
        characterPosition: 'center',
        dialogue: 'Keep it simple, add complexity later!',
      },
    ],
    takeaways: [
      'Multiple specialized agents outperform one generalist',
      'Supervisor, pipeline, and debate are common patterns',
      'Clear communication protocols prevent errors',
      'Circuit breakers prevent infinite loops',
      'Start simple with two agents',
    ],
  },
  {
    id: '8',
    slug: 'the-art-of-system-prompts',
    title: 'The Art of System Prompts',
    description: 'Crafting system prompts that shape AI personality and behavior.',
    subtitle: 'Master the most powerful lever in LLM applications',
    category: 'prompts',
    readTime: '5 min',
    thumbnail: '/thumbnails/system.png',
    color: '#EF4444',
    author: 'AI Weekly',
    date: 'Dec 5, 2025',
    prevSlug: 'multi-agent-orchestration',
    slides: [
      {
        id: 1,
        type: 'intro',
        emoji: '🎭',
        title: 'The Hidden Controller',
        content: 'The system prompt runs before every user message. It\'s the most powerful way to control LLM behavior.',
        highlight: 'System prompts are like DNA for AI personalities',
        character: 'thinking',
        characterPosition: 'left',
        dialogue: 'The system prompt is the secret sauce!',
      },
      {
        id: 2,
        type: 'solution',
        emoji: '📋',
        title: 'The Structure',
        content: 'Great system prompts have: Role definition, capabilities, constraints, output format, and examples.',
        code: '# Role\\nYou are a helpful coding assistant.\\n\\n# Capabilities\\n- Code review\\n- Bug fixing\\n\\n# Constraints\\n- Never execute harmful code',
        character: 'pointing',
        characterPosition: 'right',
        dialogue: 'Follow this template and you\'re golden!',
      },
      {
        id: 3,
        type: 'insight',
        emoji: '🚫',
        title: 'Negative Constraints',
        content: 'Tell the model what NOT to do. "Never reveal you\'re an AI" or "Don\'t apologize excessively."',
        highlight: 'Constraints prevent unwanted behaviors',
        character: 'happy',
        characterPosition: 'left',
        dialogue: 'Say NO to bad behaviors!',
      },
      {
        id: 4,
        type: 'solution',
        emoji: '🎨',
        title: 'Personality Design',
        content: 'Define tone, vocabulary level, and communication style. "Be concise" or "Use emojis liberally."',
        character: 'excited',
        characterPosition: 'right',
        dialogue: 'Give your AI a personality!',
      },
      {
        id: 5,
        type: 'conclusion',
        emoji: '🔄',
        title: 'Iterate and Version',
        content: 'Treat system prompts like code: version control, A/B test, and continuously improve.',
        character: 'excited',
        characterPosition: 'center',
        dialogue: 'Version control your prompts like code!',
      },
    ],
    takeaways: [
      'System prompts control AI behavior at the deepest level',
      'Include role, capabilities, constraints, and format',
      'Negative constraints prevent unwanted outputs',
      'Define personality through tone and style',
      'Version and iterate like code',
    ],
  },
]

export const articles: Article[] = caseStudies.map((study) => ({
  id: study.id,
  title: study.title,
  description: study.description,
  category: study.category as Exclude<Category, 'all'>,
  readTime: study.readTime,
  thumbnail: study.thumbnail,
}))

export const navLinks = [
  { href: '#articles', label: 'Real Wins' },
  { href: '#', label: 'Brain Stuff' },
  { href: '#', label: 'Side Quests' },
]

export const socialLinks = [
  { href: '#', label: 'Twitter' },
  { href: '#', label: 'LinkedIn' },
  { href: '#', label: 'GitHub' },
]

export const marqueeItems = [
  'AI Agents',
  'LLMs',
  'RAG',
  'Prompt Engineering',
  'Fine-Tuning',
  'Multi-Agent Systems',
  'AI UX',
]
